### ISSUE TITLE
`Recent uploads` missing a package

### ISSUE THREAD

**Issue by vadi2** [Mudlet/mudlet-package-repository#89]
I added the GUI Drop package and while it appears on the [entire listing](https://mudlet.github.io/mudlet-package-repository/all-packages.html), it doesn't show up in recent uploads:

![image](https://github.com/user-attachments/assets/cddc5000-69d6-49c2-bfe8-07d18821f17e)

**Comment by ZookaOnGit** [comment]
because of the capitalisation; #68

**Comment by vadi2** [comment]
Ah, closing as duplicate
